#!/bin/sh -e

PRETTY_NAME=libdrm
MAJOR=2
MINOR=4
PATCH=120
VERSION=2.4.120

mkdir temporary-builddir
DESTDIR="$PWD/temporary-builddir"

curl --location --remote-name --skip-existing https://dri.freedesktop.org/libdrm/libdrm-$VERSION.tar.xz

xz -cd libdrm-$VERSION.tar.xz | tar -x
cd libdrm-$VERSION

meson setup \
	-Dprefix=/usr \
	-Dlibdir=/usr/lib \
	-Dbuildtype=release \
	-Ddefault_library=both \
	-Dudev=false \
	-Dcairo-tests=disabled \
	-Dvalgrind=disabled \
	-Dtests=false \
	-Dman-pages=disabled \
	-Dintel=disabled \
	-Dradeon=disabled \
	-Damdgpu=disabled \
	-Dnouveau=disabled \
	-Dvmwgfx=disabled \
	-Domap=disabled \
	-Dexynos=disabled \
	-Dfreedreno=disabled \
	-Dtegra=disabled \
	-Dvc4=disabled \
	-Detnaviv=disabled \
	build

meson -C build compile
meson -C build install -d "$DESTDIR"

find "$DESTDIR/usr/lib" -type f -name '*.a'   -exec strip --strip-unneeded {} \;
find "$DESTDIR/usr/lib" -type f -name '*.so*' -exec strip --strip-unneeded {} \;

su
chown -R root:root $DESTDIR
tar -zcC $DESTDIR . | gzip > ../libdrm@$VERSION.tar.gz
exit
