#!/bin/sh -e

xz -cd libdrm-$VERSION.tar.xz | tar -x
cd libdrm-$VERSION

meson setup \
	-Dprefix=/usr \
	-Dlibdir=/usr/lib \
	-Dbuildtype=release \
	-Ddefault_library=both \
	-Dudev=false \
	-Dcairo-tests=disabled \
	-Dvalgrind=disabled \
	-Dtests=false \
	-Dman-pages=disabled \
	-Dintel=disabled \
	-Dradeon=disabled \
	-Damdgpu=disabled \
	-Dnouveau=disabled \
	-Dvmwgfx=disabled \
	-Domap=disabled \
	-Dexynos=disabled \
	-Dfreedreno=disabled \
	-Dtegra=disabled \
	-Dvc4=disabled \
	-Detnaviv=disabled \
	build

meson -C build compile
meson -C build install -d "$DESTDIR"

find "$DESTDIR/usr/lib" -type f -name '*.a'   -exec strip --strip-unneeded {} \;
find "$DESTDIR/usr/lib" -type f -name '*.so*' -exec strip --strip-unneeded {} \;
