#!/bin/sh -e

PRETTY_NAME=linux-firmware
MAJOR=
MINOR=
PATCH=
VERSION=git

mkdir temporary-builddir
DESTDIR="$PWD/temporary-builddir"

git clone https://gitlab.manjaro.org/manjaro-arm/packages/community/ap6256-firmware.git
git clone https://github.com/Caesar-github/rkwifibt.git

install -Dm644 ap6256-firmware/brcmfmac43456-sdio.clm_blob "$DESTDIR/usr/lib/firmware/brcmfmac43456-sdio.clm_blob"
install -Dm644 rkwifibt/firmware/broadcom/AP6256/bt/BCM4345C5.hcd "$DESTDIR/usr/lib/firmware/BCM4345C5.hcd"
install -Dm644 rkwifibt/firmware/broadcom/AP6256/wifi/fw_bcm43456c5_ag.bin "$DESTDIR/usr/lib/firmware/brcmfmac43456-sdio.bin"
install -Dm644 rkwifibt/firmware/broadcom/AP6256/wifi/nvram_ap6256.txt "$DESTDIR/usr/lib/firmware/brcmfmac43456-sdio.txt"
sed -i 's/ccode=DE/ccode=all/' "$DESTDIR/usr/lib/firmware/brcmfmac43456-sdio.txt"
ln -sf brcmfmac43456-sdio.txt "$DESTDIR/usr/lib/firmware/brcmfmac43456-sdio.pinebook-pro.txt"

doas chown -R root:root $DESTDIR
doas sh -c "tar -zcC $DESTDIR . | gzip > ../linux-firmware@$VERSION.tar.gz"
