#!/bin/sh -e

xz -cd linux-$VERSION.tar.xz | tar -x

# Apply device-specific patches
for p in ../void-packages/srcpkgs/pinebookpro-kernel/patches/*.patch
do
	patch -p1 < ../void-packages/srcpkgs/pinebookpro-kernel/patches/$p 
done

mv ../pinebook-pro-config config

make oldconfig
make Image
make dtbs
make dtbs_install INSTALL_DTBS_PATH="$DESTDIR/boot/dtbs"
cp arch/arm64/boot/Image "$DESTDIR/boot/Image"

install -Dm644 ../extlinux.conf "$DESTDIR/boot/extlinux/extlinux.conf"

su
chown -R root:root $DESTDIR
tar -c $DESTDIR/* | gzip2 > linux@$VERSION.tar.gz
exit
