#!/bin/sh -e

export DEPENDENCIES="bc bison dtc findutils flex ncurses perl u-boot-tools util-linux"
export INFO="The Linux kernel"
export PRETTY_NAME="linux"
export SOURCES="https://mirrors.edge.kernel.org/pub/linux/kernel/v$MAJOR.x/linux-$VERSION.tar.xz"
export MAJOR="6"
export MINOR="9"
export PATCH="4"
export VERSION="$MAJOR.$MINOR.$PATCH"
