#!/bin/sh -e

export DEPENDENCIES="bc bison dtc findutils flex linux-firmware ncurses perl util-linux"
export INFO="The Linux kernel"
export PRETTY_NAME="linux"
export SOURCES="https://mirrors.edge.kernel.org/pub/linux/kernel/v$MAJOR.x/linux-$VERSION.tar.xz"
export SOURCES="$SOURCES files/pinebook-pro-config"
export SOURCES="$SOURCES files/extlinux.conf"
export MAJOR="6"
export MINOR="13"
export PATCH="3"
export VERSION="$MAJOR.$MINOR.$PATCH"
