#!/bin/sh -e

PRETTY_NAME=mesa
MAJOR=23
MINOR=1
PATCH=1
VERSION=23.1.1

mkdir temporary-builddir
DESTDIR="$PWD/temporary-builddir"

curl --location --remote-name --skip-existing https://archive.mesa3d.org/mesa-$VERSION.tar.xz

xz -cd mesa-$VERSION.tar.xz | tar -x
cd mesa-$VERSION

meson setup \
	-Dprefix=/usr \
	-Dsysconfdir=/etc \
	-Dmandir=/usr/share/man \
	-Dlocalstatedir=/var \
	-Dbuildtype=release \
	-Ddefault_library=both \
	-Dplatforms=wayland \
	-Dglx=disabled \
	-Degl=enabled \
	-Dgles1=enabled \
	-Dgles2=enabled \
	-Degl-native-platform=wayland \
	-Dvalgrind=disabled \
	-Dzstd=disabled \
	-Dglvnd=enabled \
	-Dvulkan-drivers= \
	-Dgallium-drivers=panfrost \
	-Dllvm=disabled \
	build

meson -C build compile
meson -C build install -d "$DESTDIR"

doas chown -R root:root $DESTDIR
doas sh -c "tar -zcC $DESTDIR . | gzip > ../mesa@$VERSION.tar.gz"
