#!/bin/sh -e

PRETTY_NAME=ffmpeg
MAJOR=6
MINOR=1
PATCH=
VERSION=6.1

mkdir temporary-builddir
DESTDIR="$PWD/temporary-builddir"

curl --location --remote-name --skip-existing https://dev.gentoo.org/~chewi/distfiles/ffmpeg-rpi-$VERSION.patch
curl --location --remote-name --skip-existing https://ffmpeg.org/releases/ffmpeg-$VERSION.tar.xz

xz -cd ffmpeg-$VERSION.tar.xz | tar -x
cd ffmpeg-$VERSION

patch -p1 < ../ffmpeg-rpi-$VERSION.patch

./configure \
	--prefix=/usr \
	--disable-bzlib \
	--disable-debug \
	--disable-libass \
	--disable-libwebp \
	--disable-libxcb \
	--disable-libxcb-shm \
	--disable-libxcb-xfixes \
	--disable-libxcb-shape \
	--disable-libxml2 \
	--disable-libxvid \
	--disable-lzma \
	--disable-network \
	--disable-nonfree \
	--disable-openssl \
	--disable-xlib \
	--disable-zlib \
	--enable-alsa \
	--enable-gpl \
	--enable-libdrm \
	--enable-libmp3lame \
	--enable-libopus \
	--enable-libvpx \
	--enable-libvorbis \
	--enable-sdl2 \
	--enable-shared \
	--enable-stripping \
	--enable-libx264 \
	--enable-libx265

make
make DESTDIR=$DESTDIR install-strip

rm -rf "$DESTDIR/usr/share/ffmpeg/examples"

su
chown -R root:root $DESTDIR
tar -zcC $DESTDIR . | gzip > ../ffmpeg@$VERSION.tar.gz
exit
